# Use a Node base image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json ./
COPY package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of your app's source code from your host to your image filesystem.
COPY . .

# Expose a port that matches the port your app runs on
EXPOSE 3000

# Command to run your app
CMD ["npm", "start"]
